<?php
namespace Neos\Flow\Persistence\Doctrine\Migrations;

use Doctrine\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your needs! This block will be used as the migration description if getDescription() is not used.
 */
class Version20190801192710 extends AbstractMigration
{

    /**
     * @return string
     */
    public function getDescription()
    {
        return '';
    }

    /**
     * @param Schema $schema
     * @return void
     */
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on "mysql".');
        
        $this->addSql('CREATE TABLE ewert_webpush_domain_model_subscription (persistence_object_identifier VARCHAR(40) NOT NULL, endpoint VARCHAR(512) NOT NULL, expirationtime INT DEFAULT NULL, p256dh VARCHAR(512) NOT NULL, auth VARCHAR(512) NOT NULL, PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ewert_webpush_domain_model_message (persistence_object_identifier VARCHAR(40) NOT NULL, title VARCHAR(512) NOT NULL, direction VARCHAR(255) DEFAULT NULL, lang VARCHAR(255) DEFAULT NULL, body LONGTEXT DEFAULT NULL, tag VARCHAR(255) DEFAULT NULL, image VARCHAR(255) DEFAULT NULL, icon VARCHAR(255) DEFAULT NULL, badge VARCHAR(255) DEFAULT NULL, vibrate LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:simple_array)\', timestamp INT DEFAULT NULL, renotify TINYINT(1) DEFAULT NULL, silent TINYINT(1) DEFAULT NULL, requireinteraction TINYINT(1) DEFAULT NULL, url VARCHAR(255) DEFAULT NULL, actions JSON DEFAULT NULL COMMENT \'(DC2Type:json_array)\', PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
    }

    /**
     * @param Schema $schema
     * @return void
     */
    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on "mysql".');
        
        $this->addSql('DROP TABLE ewert_webpush_domain_model_subscription');
        $this->addSql('DROP TABLE ewert_webpush_domain_model_message');
    }
}