Neos:
  Flow:
    mvc:
      routes:
        'Ewert.WebPush': true
  Neos:
    fusion:
      autoInclude:
        'Ewert.WebPush': true
    modules:
      'management':
        submodules:
          'webPush':
            label: 'Push Messages'
            controller: 'Ewert\WebPush\Controller\MessageController'
            description: 'Send Push-Messages'
            icon: 'icon-comment-dots'

Ewert:
  WebPush:
    vapid:
      publicKey: ''
      privateKey: ''
