Neos:
  Neos:
    modules:
      'management':
        submodules:
          'webPush':
            label: 'Push Messages'
            controller: 'Ewert\WebPush\Controller\BackendController'
            description: 'Send Push-Messages'
            icon: 'icon-comment-dots'
