Neos:
  Flow:
    mvc:
      routes:
        'Ewert.WebPush': true
  Neos:
    fusion:
      autoInclude:
        'Ewert.WebPush': true
    modules:
      'management':
        submodules:
          'webPush':
            label: 'Push Messages'
            controller: 'Ewert\WebPush\Controller\MessageController'
            description: 'Send Push-Messages'
            icon: 'icon-comment-dots'

Ewert:
  WebPush:
    vapid:
      publicKey: 'BEVvo1UcO4UA_L_tt_Wa9KMLrNKB2DMF1q3j4B8XCSsBHXcdDJlLTnUD0fMDYNETLHEbyY1zgYfZ_1OG7vG1roA'
      privateKey: 'iy6cwuzCOIW3aodvOnGkFXBojwV79QvHfeL40fdo5qg'
